export * from "@sovereign/control-plane-contract";

export const IPC_CHANNELS = {
  getState: "runtime:get-state",
  chooseWorkspace: "runtime:choose-workspace",
  readProjectWorkspaces: "project:workspaces-read",
  chooseProjectWorkspace: "project:workspace-choose",
  selectProjectWorkspace: "project:workspace-select",
  start: "runtime:start",
  stop: "runtime:stop",
  refresh: "runtime:refresh",
  getManifest: "runtime:get-manifest",
  getAuditReceipts: "runtime:get-audit-receipts",
  getResourceSnapshot: "resources:get-snapshot",
  getHostStartupState: "host:get-startup-state",
  setLaunchAtLogin: "host:set-launch-at-login",
  getRuns: "runs:list",
  getRun: "runs:get",
  cancelRun: "runs:cancel",
  getTaskWorkspace: "tasks:snapshot",
  getTaskDetail: "tasks:get",
  getTaskCoordinationInbox: "tasks:coordination-inbox",
  sendTaskUserMessage: "tasks:message-user",
  invokeTool: "desktop:invoke-tool",
  copyConnectionBundle: "runtime:copy-connection-bundle",
  rotateCredentials: "runtime:rotate-credentials",
  setAutoStart: "runtime:set-auto-start",
  setUnattendedWorkspaceAccess: "runtime:set-unattended-workspace-access",
  setPermissionProfile: "runtime:set-permission-profile",
  setWebBridgeUrl: "runtime:set-web-bridge-url",
  configureSecureTunnel: "runtime:configure-secure-tunnel",
  setSecureTunnelAutomation: "runtime:set-secure-tunnel-automation",
  chooseSecureTunnelExecutable: "runtime:choose-secure-tunnel-executable",
  startSecureTunnel: "runtime:start-secure-tunnel",
  stopSecureTunnel: "runtime:stop-secure-tunnel",
  refreshSecureTunnel: "runtime:refresh-secure-tunnel",
  setUiScale: "ui:set-scale",
  approvalGetCurrent: "approval:get-current",
  approvalResolve: "approval:resolve",
  stateChanged: "runtime:state-changed",
} as const;
